[package]
name = "apng-compiler"
version = "0.1.0"
authors = ["anekos <anekos@snca.net>"]
edition = "2018"

[[bin]]
path = "src/main.rs"
name = "apngc"

[dependencies]
apng-encoder = { path = "../" }
failure = "*"
image = "0.21"
indicatif = "0.14.0"
